<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Department';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$department = $form->get('department');
$department->setAttribute('class', 'form-control');
$department->setAttribute('placeholder', 'Nombre del Departamento');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('department', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($department) ?>
    <?= $this->formElement($department) ?>
    <?= $this->formElementErrors()->render($department, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();