<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Titulo de Proyecto');

$st_date = $form->get('st_date');
$st_date->setAttribute('class', 'form-control');
$st_date->setAttribute('placeholder', 'Fecha');

$complete = $form->get('complete');
$complete->setAttribute('class', 'form-control');
$complete->setAttribute('placeholder', 'Complete');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('project', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($st_date) ?>
    <?= $this->formElement($st_date) ?>
    <?= $this->formElementErrors()->render($st_date, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($complete) ?>
    <?= $this->formElement($complete) ?>
    <?= $this->formElementErrors()->render($complete, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();